In [36]:
import numpy as np
import scipy as sp

In [3]:
a = np.random.randint(low=1, high=5, size=(4,4))

In [4]:
a

array([[3, 3, 2, 1],
       [4, 1, 2, 3],
       [4, 3, 3, 2],
       [4, 4, 3, 4]])

In [5]:
x = np.random.randint(low=1, high=5, size=(1,4))

In [6]:
x

array([[3, 4, 1, 2]])

In [7]:
a - x

array([[ 0, -1,  1, -1],
       [ 1, -3,  1,  1],
       [ 1, -1,  2,  0],
       [ 1,  0,  2,  2]])

In [8]:
y = np.concatenate((a - x, a + x))
y

array([[ 0, -1,  1, -1],
       [ 1, -3,  1,  1],
       [ 1, -1,  2,  0],
       [ 1,  0,  2,  2],
       [ 6,  7,  3,  3],
       [ 7,  5,  3,  5],
       [ 7,  7,  4,  4],
       [ 7,  8,  4,  6]])

In [9]:
W = np.arange(8) / 10
W

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7])

In [10]:
np.dot(W, y)

array([15.6, 14.6,  9. , 11. ])

In [11]:
[np.sum(y[:,i] * W) for i in range(4)]

[15.6, 14.600000000000001, 9.0, 11.0]

In [12]:
np.expand_dims(x.squeeze(), 1)

array([[3],
       [4],
       [1],
       [2]])

In [13]:
y.shape

(8, 4)

In [14]:
z = np.multiply(np.expand_dims(y, 1), np.expand_dims(y, 2))
z

array([[[ 0,  0,  0,  0],
        [ 0,  1, -1,  1],
        [ 0, -1,  1, -1],
        [ 0,  1, -1,  1]],

       [[ 1, -3,  1,  1],
        [-3,  9, -3, -3],
        [ 1, -3,  1,  1],
        [ 1, -3,  1,  1]],

       [[ 1, -1,  2,  0],
        [-1,  1, -2,  0],
        [ 2, -2,  4,  0],
        [ 0,  0,  0,  0]],

       [[ 1,  0,  2,  2],
        [ 0,  0,  0,  0],
        [ 2,  0,  4,  4],
        [ 2,  0,  4,  4]],

       [[36, 42, 18, 18],
        [42, 49, 21, 21],
        [18, 21,  9,  9],
        [18, 21,  9,  9]],

       [[49, 35, 21, 35],
        [35, 25, 15, 25],
        [21, 15,  9, 15],
        [35, 25, 15, 25]],

       [[49, 49, 28, 28],
        [49, 49, 28, 28],
        [28, 28, 16, 16],
        [28, 28, 16, 16]],

       [[49, 56, 28, 42],
        [56, 64, 32, 48],
        [28, 32, 16, 24],
        [42, 48, 24, 36]]])

In [18]:
np.dot(z.T, np.arange(8) / 8)

array([[129.  , 128.  ,  69.  ,  89.5 ],
       [128.  , 134.25,  68.  ,  88.75],
       [ 69.  ,  68.  ,  38.75,  48.5 ],
       [ 89.5 ,  88.75,  48.5 ,  65.25]])

In [26]:
np.dot(np.stack((np.eye(4), np.eye(4))).T, [.1, .2])

array([[0.3, 0. , 0. , 0. ],
       [0. , 0.3, 0. , 0. ],
       [0. , 0. , 0.3, 0. ],
       [0. , 0. , 0. , 0.3]])

In [51]:
def sqrtm(X: np.ndarray) -> np.ndarray:
    # Computing diagonalization
    evalues, evectors = np.linalg.eig(X)
    # Ensuring square root matrix exists
    assert (evalues >= 0).all()
    return evectors * np.sqrt(evalues) @ np.linalg.inv(evectors)

def rot(alpha):
    return np.array([[np.cos(alpha), -np.sin(alpha)],
                    [np.sin(alpha),  np.cos(alpha)]])

In [33]:
eval, evec = np.linalg.eig([[1, 0.5], [0.5, 2]])

In [48]:
evec

array([[-0.92387953, -0.38268343],
       [ 0.38268343, -0.92387953]])

In [50]:
np.arccos(0.92387953) * 180 / np.pi

22.500000375992585

In [58]:
R = rot(0/180.0 * np.pi)
R

array([[ 1., -0.],
       [ 0.,  1.]])

In [59]:
R @ np.diag([4, 1]) @ R.T

array([[4., 0.],
       [0., 1.]])