In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3])

In [4]:
x

array([1, 2, 3])

In [5]:
x.shape

(3,)

In [7]:
np.atleast_2d(x)

array([[1, 2, 3]])

In [8]:
np.atleast_2d(x).shape

(1, 3)

In [9]:
np.atleast_2d(x).T

array([[1],
       [2],
       [3]])

In [10]:
np.atleast_2d(x).T.shape

(3, 1)